SAGA C++ API: dump_directory.cpp File Reference
dump_directory.cpp File Reference
#include <saga/saga.hpp>
#include "saga-advert.hpp"
Functions
void advert_dump_directory (std::string advertURL, std::string indent, std::string parentcwd)
Function Documentation
void advert_dump_directory (std::string advertURL, std::string indent, std::string parentcwd)
References advert_dump_directory(), saga::url::get_string(), and SAGA_GUARDED_EXEC.
Referenced by advert_dump_directory(), and main().