SAGA C++ API: run_benchmarks_impl.cpp File Reference
run_benchmarks_impl.cpp File Reference
#include <iostream>
#include <vector>
#include <saga/saga.hpp>
#include "saga-file.hpp"
#include <saga/saga/adaptors/utils/high_resolution_timer.hpp>
#include <boost/lexical_cast.hpp>
#include <boost/version.hpp>
Defines
#define ITERATIONS 100
Functions
void run_benchmarks (std::string smallFile, std::string largeFile, std::string targetDir, int copyIterations)
Define Documentation
#define ITERATIONS 100
Referenced by run_benchmarks().
Function Documentation
void run_benchmarks (std::string smallFile, std::string largeFile, std::string targetDir, int copyIterations)
References saga::task_container::add_task(), saga::name_space::entry::copy(), ITERATIONS, saga::filesystem::Overwrite, SAGA_GUARDED_EXEC, and saga::task_container::wait().
Referenced by main().