SAGA C++ API: job_submit_impl.cpp File Reference
job_submit_impl.cpp File Reference
#include <saga/saga.hpp>
#include "saga-job.hpp"
Functions
void job_submit (std::string service_url, std::string exe, std::vector< std::string > argvec)
Function Documentation
void job_submit (std::string service_url, std::string exe, std::vector< std::string > argvec)
References saga::attributes::common_false, saga::job::service::create_job(), saga::job::attributes::description_arguments, saga::job::attributes::description_executable, saga::job::attributes::description_interactive, saga::job::job::get_job_id(), saga::job::job::run(), SAGA_GUARDED_EXEC, saga::detail::attribute< Derived >::set_attribute(), and saga::detail::attribute< Derived >::set_vector_attribute().
Referenced by main().