SAGA C++ API: run_benchmarks_impl.cpp File Reference
run_benchmarks_impl.cpp File Reference
#include <iostream>
#include <vector>
#include <saga/saga.hpp>
#include "saga-job.hpp"
#include <saga/saga/adaptors/utils/high_resolution_timer.hpp>
#include <boost/lexical_cast.hpp>
#include <boost/version.hpp>
Defines
#define ITERATIONS 100
Functions
void run_benchmarks (std::string rmURL)
Define Documentation
#define ITERATIONS 100
Function Documentation
void run_benchmarks (std::string rmURL)
References saga::task_container::add_task(), saga::job::service::create_job(), ITERATIONS, saga::job::job::run(), SAGA_GUARDED_EXEC, saga::detail::attribute< Derived >::set_attribute(), and saga::task_container::wait().