SAGA C++ API: lite-test.cpp File Reference
lite-test.cpp File Reference
#include <saga/saga.hpp>
Functions
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
References saga::filesystem::Current, saga::url::get_host(), saga::url::get_path(), saga::filesystem::file::get_size(), saga::filesystem::file::read(), saga::filesystem::Read, saga::filesystem::file::seek(), and saga::url::set_host().