SAGA C++ API: saga Namespace Reference
saga Namespace Reference
Detailed Description
The SAGA root namespace.
Classes
class attribute
Brief description starts here.
class const_buffer
Encapsulates I/O operations.
class mutable_buffer
Brief description starts here.
class context
The saga::context class provides the functionality of a security information container.
class exception
class not_implemented
class parameter_exception
class incorrect_url
class bad_parameter
class state_exception
class already_exists
class does_not_exist
class incorrect_state
class security_exception
class permission_denied
class authorization_failed
class authentication_failed
class timeout
class no_success
class metric
Brief description starts here.
class monitorable
The monitorable interface is implemented by those SAGA objects which can be monitored, i.e. which have one or more associated metrics.
class steerable
The steerable interface is implemented by saga objects which can be steered, i.e. which have writable metrics, and which might allow to add new metrics.
class object
Brief description starts here.
class permissions
The SAGA permission interface.
class session
Almost all SAGA objects are created in a SAGA session, and are associated with this (and only this) session for their whole life time.
class task
Brief description starts here.
struct task_base
Brief description starts here.
class task_container
Handles a large number of asynchronous operations.
class url
SAGA's implementation of an RFC 1630 compliant URL Class.
class uuid
Brief description starts here.
Namespaces
namespace attributes
namespace detail
namespace advert
The Advert Service API package.
namespace cpr
The Checkpoint and Recovery (CPR) API package.
namespace filesystem
The File Management API package.
namespace job
The Job Management API package.
namespace name_space
The Name Space API package.
namespace replica
The Replica Management API package.
namespace rpc
The Remote Procedure Call API package.
namespace sd
namespace stream
The Streams API package.
Enumerations
enum error {
NotImplemented = 1,
IncorrectURL = 2,
BadParameter = 3,
AlreadyExists = 4,
DoesNotExist = 5,
IncorrectState = 6,
PermissionDenied = 7,
AuthorizationFailed = 8,
AuthenticationFailed = 9,
Timeout = 10,
NoSuccess = 11
}
Brief description starts here.
Functions
mutable_buffer buffer (void *data, saga::size_t size)
const_buffer buffer (void const *data, saga::size_t size)
template<typename PodType, std::size_t N>
mutable_buffer buffer (PodType(&data)[N])
template<typename PodType, std::size_t N>
const_buffer buffer (PodType const (&data)[N])
template<typename PodType, std::size_t N>
mutable_buffer buffer (PodType(&data)[N], saga::size_t max_size)
template<typename PodType, std::size_t N>
const_buffer buffer (PodType const (&data)[N], saga::size_t max_size)
template<typename PodType, typename Allocator>
mutable_buffer buffer (std::vector< PodType, Allocator > &data)
template<typename PodType, typename Allocator>
const_buffer buffer (std::vector< PodType, Allocator > const &data)
template<typename PodType, typename Allocator>
mutable_buffer buffer (std::vector< PodType, Allocator > &data, saga::size_t max_size)
template<typename PodType, typename Allocator>
const_buffer buffer (std::vector< PodType, Allocator > const &data, saga::size_t max_size)
template<typename Char, typename Traits, typename Allocator>
const_buffer buffer (std::basic_string< Char, Traits, Allocator > const &data)
template<typename Char, typename Traits, typename Allocator>
const_buffer buffer (std::basic_string< Char, Traits, Allocator > const &data, saga::size_t max_size)
template
SAGA_ADVERT_PACKAGE_EXPORT
saga::advert::entry & task::get_result< saga::advert::entry > ()
template
SAGA_ADVERT_PACKAGE_EXPORT
saga::advert::directory & task::get_result< saga::advert::directory > ()
template
SAGA_ADVERT_PACKAGE_EXPORT
saga::object & task::get_result< saga::object > ()
unsigned long get_advert_package_version (void)
unsigned long get_advert_package_api_version (void)
template
SAGA_CPR_PACKAGE_EXPORT
saga::cpr::job & task::get_result< saga::cpr::job > ()
template
SAGA_CPR_PACKAGE_EXPORT
saga::cpr::checkpoint & task::get_result< saga::cpr::checkpoint > ()
template
SAGA_CPR_PACKAGE_EXPORT
saga::cpr::directory & task::get_result< saga::cpr::directory > ()
template
SAGA_CPR_PACKAGE_EXPORT
saga::cpr::description & task::get_result< saga::cpr::description > ()
template
SAGA_CPR_PACKAGE_EXPORT
saga::cpr::self & task::get_result< saga::cpr::self > ()
template
SAGA_CPR_PACKAGE_EXPORT
saga::cpr::service & task::get_result< saga::cpr::service > ()
unsigned long get_cpr_package_version (void)
unsigned long get_cpr_package_api_version (void)
template
SAGA_FILE_PACKAGE_EXPORT
saga::filesystem::file & task::get_result< saga::filesystem::file > ()
template
SAGA_FILE_PACKAGE_EXPORT
saga::filesystem::directory & task::get_result< saga::filesystem::directory > ()
unsigned long get_file_package_version (void)
unsigned long get_file_package_api_version (void)
template
SAGA_JOB_PACKAGE_EXPORT
saga::job::job & task::get_result< saga::job::job > ()
template
SAGA_JOB_PACKAGE_EXPORT
saga::job::state & task::get_result< saga::job::state > ()
template
SAGA_JOB_PACKAGE_EXPORT
saga::job::ostream & task::get_result< saga::job::ostream > ()
template
SAGA_JOB_PACKAGE_EXPORT
saga::job::istream & task::get_result< saga::job::istream > ()
template
SAGA_JOB_PACKAGE_EXPORT
saga::job::self & task::get_result< saga::job::self > ()
template
SAGA_JOB_PACKAGE_EXPORT
saga::job::description & task::get_result< saga::job::description > ()
template
SAGA_JOB_PACKAGE_EXPORT
saga::job::service & task::get_result< saga::job::service > ()
unsigned long get_job_package_version (void)
unsigned long get_job_package_api_version (void)
template
SAGA_NAMESPACE_PACKAGE_EXPORT
saga::name_space::directory & task::get_result< saga::name_space::directory > ()
template
SAGA_NAMESPACE_PACKAGE_EXPORT
saga::name_space::entry & task::get_result< saga::name_space::entry > ()
unsigned long get_namespace_package_version ()
unsigned long get_namespace_package_api_version ()
template
SAGA_REPLICA_PACKAGE_EXPORT
saga::replica::logical_file & task::get_result< saga::replica::logical_file > ()
template
SAGA_REPLICA_PACKAGE_EXPORT
saga::replica::logical_directory & task::get_result< saga::replica::logical_directory > ()
unsigned long get_replica_package_version (void)
unsigned long get_replica_package_api_version (void)
template
SAGA_RPC_PACKAGE_EXPORT
saga::rpc::rpc & task::get_result< saga::rpc::rpc > ()
unsigned long get_rpc_package_version ()
unsigned long get_rpc_package_api_version ()
template
SAGA_SD_PACKAGE_EXPORT
std::vector
< saga::sd::service_description > & task::get_result< std::vector< saga::sd::service_description > > ()
template
SAGA_SD_PACKAGE_EXPORT
saga::sd::discoverer & task::get_result< saga::sd::discoverer > ()
unsigned long get_sd_package_version ()
unsigned long get_sd_package_api_version ()
template
SAGA_STREAM_PACKAGE_EXPORT
saga::stream::stream & task::get_result< saga::stream::stream > ()
template
SAGA_STREAM_PACKAGE_EXPORT
saga::stream::server & task::get_result< saga::stream::server > ()
template
SAGA_STREAM_PACKAGE_EXPORT
saga::stream::activity & task::get_result< saga::stream::activity > ()
template
SAGA_STREAM_PACKAGE_EXPORT
std::vector
< saga::stream::activity > & task::get_result< std::vector< saga::stream::activity > > ()
unsigned long get_stream_package_version ()
unsigned long get_stream_package_api_version ()
template SAGA_EXPORT std::string & task::get_result< std::string > ()
template SAGA_EXPORT
std::vector< std::string > & task::get_result< std::vector< std::string > > ()
template SAGA_EXPORT saga::size_t & task::get_result< saga::size_t > ()
template SAGA_EXPORT
saga::ssize_t & task::get_result< saga::ssize_t > ()
template SAGA_EXPORT saga::off_t & task::get_result< saga::off_t > ()
template SAGA_EXPORT
saga::context & task::get_result< saga::context > ()
template SAGA_EXPORT saga::url & task::get_result< saga::url > ()
template SAGA_EXPORT
std::vector< saga::url > & task::get_result< std::vector< saga::url > > ()
std::ostream & operator<< (std::ostream &os, url const &u)
Brief description starts here.
std::istream & operator>> (std::istream &is, url &u)
Brief description starts here.
bool operator== (saga::url const &lhs, saga::url const &rhs)
Brief description starts here.
bool operator< (saga::url const &lhs, saga::url const &rhs)
Brief description starts here.
unsigned long get_engine_version (void)
Brief description starts here.
unsigned long get_saga_version (void)
Brief description starts here.
SAGA_EXPORT char const BOOST_PP_CAT (saga_check_version_, BOOST_PP_CAT(SAGA_VERSION_MAJOR, BOOST_PP_CAT(_, SAGA_VERSION_MINOR)))[]
Brief description starts here.
Variables
char const SAGA_CHECK_VERSION [] = BOOST_PP_STRINGIZE(SAGA_CHECK_VERSION)
Enumeration Type Documentation
enum saga::error
Brief description starts here.
Enumerator:
NotImplemented
IncorrectURL
BadParameter
AlreadyExists
DoesNotExist
IncorrectState
PermissionDenied
AuthorizationFailed
AuthenticationFailed
Timeout
NoSuccess
Function Documentation
mutable_buffer saga::buffer (void * data, saga::size_t size) [inline]
Referenced by file_cat(), and get_hostname().
const_buffer saga::buffer (void const * data, saga::size_t size) [inline]
template<typename PodType, std::size_t N> mutable_buffer saga::buffer (PodType(&) data[N]) [inline]
template<typename PodType, std::size_t N> const_buffer saga::buffer (PodType const (&) data[N]) [inline]
template<typename PodType, std::size_t N> mutable_buffer saga::buffer (PodType(&) data[N], saga::size_t max_size) [inline]
template<typename PodType, std::size_t N> const_buffer saga::buffer (PodType const (&) data[N], saga::size_t max_size) [inline]
template<typename PodType, typename Allocator> mutable_buffer saga::buffer (std::vector< PodType, Allocator > & data) [inline]
template<typename PodType, typename Allocator> const_buffer saga::buffer (std::vector< PodType, Allocator > const & data) [inline]
template<typename PodType, typename Allocator> mutable_buffer saga::buffer (std::vector< PodType, Allocator > & data, saga::size_t max_size) [inline]
template<typename PodType, typename Allocator> const_buffer saga::buffer (std::vector< PodType, Allocator > const & data, saga::size_t max_size) [inline]
template<typename Char, typename Traits, typename Allocator> const_buffer saga::buffer (std::basic_string< Char, Traits, Allocator > const & data) [inline]
template<typename Char, typename Traits, typename Allocator> const_buffer saga::buffer (std::basic_string< Char, Traits, Allocator > const & data, saga::size_t max_size) [inline]
Referenced by get_hostname(), and job_run().
template SAGA_ADVERT_PACKAGE_EXPORT saga::advert::entry& saga::task::get_result< saga::advert::entry > ()
template SAGA_ADVERT_PACKAGE_EXPORT saga::advert::directory& saga::task::get_result< saga::advert::directory > ()
template SAGA_ADVERT_PACKAGE_EXPORT saga::object& saga::task::get_result< saga::object > ()
SAGA_ADVERT_PACKAGE_EXPORT unsigned long saga::get_advert_package_version (void)
References SAGA_VERSION_PACKAGE_ADVERT_FULL.
SAGA_ADVERT_PACKAGE_EXPORT unsigned long saga::get_advert_package_api_version (void)
References SAGA_VERSION_PACKAGE_ADVERT_API.
template SAGA_CPR_PACKAGE_EXPORT saga::cpr::job& saga::task::get_result< saga::cpr::job > ()
template SAGA_CPR_PACKAGE_EXPORT saga::cpr::checkpoint& saga::task::get_result< saga::cpr::checkpoint > ()
template SAGA_CPR_PACKAGE_EXPORT saga::cpr::directory& saga::task::get_result< saga::cpr::directory > ()
template SAGA_CPR_PACKAGE_EXPORT saga::cpr::description& saga::task::get_result< saga::cpr::description > ()
template SAGA_CPR_PACKAGE_EXPORT saga::cpr::self& saga::task::get_result< saga::cpr::self > ()
template SAGA_CPR_PACKAGE_EXPORT saga::cpr::service& saga::task::get_result< saga::cpr::service > ()
SAGA_CPR_PACKAGE_EXPORT unsigned long saga::get_cpr_package_version (void)
References SAGA_VERSION_PACKAGE_CPR_FULL.
SAGA_CPR_PACKAGE_EXPORT unsigned long saga::get_cpr_package_api_version (void)
References SAGA_VERSION_PACKAGE_CPR_API.
template SAGA_FILE_PACKAGE_EXPORT saga::filesystem::file& saga::task::get_result< saga::filesystem::file > ()
template SAGA_FILE_PACKAGE_EXPORT saga::filesystem::directory& saga::task::get_result< saga::filesystem::directory > ()
SAGA_FILE_PACKAGE_EXPORT unsigned long saga::get_file_package_version (void)
References SAGA_VERSION_PACKAGE_FILE_FULL.
SAGA_FILE_PACKAGE_EXPORT unsigned long saga::get_file_package_api_version (void)
References SAGA_VERSION_PACKAGE_FILE_API.
template SAGA_JOB_PACKAGE_EXPORT saga::job::job& saga::task::get_result< saga::job::job > ()
template SAGA_JOB_PACKAGE_EXPORT saga::job::state& saga::task::get_result< saga::job::state > ()
template SAGA_JOB_PACKAGE_EXPORT saga::job::ostream& saga::task::get_result< saga::job::ostream > ()
template SAGA_JOB_PACKAGE_EXPORT saga::job::istream& saga::task::get_result< saga::job::istream > ()
template SAGA_JOB_PACKAGE_EXPORT saga::job::self& saga::task::get_result< saga::job::self > ()
template SAGA_JOB_PACKAGE_EXPORT saga::job::description& saga::task::get_result< saga::job::description > ()
template SAGA_JOB_PACKAGE_EXPORT saga::job::service& saga::task::get_result< saga::job::service > ()
SAGA_JOB_PACKAGE_EXPORT unsigned long saga::get_job_package_version (void)
References SAGA_VERSION_PACKAGE_JOB_FULL.
SAGA_JOB_PACKAGE_EXPORT unsigned long saga::get_job_package_api_version (void)
References SAGA_VERSION_PACKAGE_JOB_API.
template SAGA_NAMESPACE_PACKAGE_EXPORT saga::name_space::directory& saga::task::get_result< saga::name_space::directory > ()
template SAGA_NAMESPACE_PACKAGE_EXPORT saga::name_space::entry& saga::task::get_result< saga::name_space::entry > ()
SAGA_NAMESPACE_PACKAGE_EXPORT unsigned long saga::get_namespace_package_version ()
References SAGA_VERSION_PACKAGE_NAMESPACE_FULL.
SAGA_NAMESPACE_PACKAGE_EXPORT unsigned long saga::get_namespace_package_api_version ()
References SAGA_VERSION_PACKAGE_NAMESPACE_API.
template SAGA_REPLICA_PACKAGE_EXPORT saga::replica::logical_file& saga::task::get_result< saga::replica::logical_file > ()
template SAGA_REPLICA_PACKAGE_EXPORT saga::replica::logical_directory& saga::task::get_result< saga::replica::logical_directory > ()
SAGA_REPLICA_PACKAGE_EXPORT unsigned long saga::get_replica_package_version (void)
References SAGA_VERSION_PACKAGE_REPLICA_FULL.
SAGA_REPLICA_PACKAGE_EXPORT unsigned long saga::get_replica_package_api_version (void)
References SAGA_VERSION_PACKAGE_REPLICA_API.
template SAGA_RPC_PACKAGE_EXPORT saga::rpc::rpc& saga::task::get_result< saga::rpc::rpc > ()
SAGA_RPC_PACKAGE_EXPORT unsigned long saga::get_rpc_package_version ()
References SAGA_VERSION_PACKAGE_RPC_FULL.
SAGA_RPC_PACKAGE_EXPORT unsigned long saga::get_rpc_package_api_version ()
References SAGA_VERSION_PACKAGE_RPC_API.
template SAGA_SD_PACKAGE_EXPORT std::vector<saga::sd::service_description>& saga::task::get_result< std::vector< saga::sd::service_description > > ()
template SAGA_SD_PACKAGE_EXPORT saga::sd::discoverer& saga::task::get_result< saga::sd::discoverer > ()
SAGA_SD_PACKAGE_EXPORT unsigned long saga::get_sd_package_version ()
References SAGA_VERSION_PACKAGE_SD_FULL.
SAGA_SD_PACKAGE_EXPORT unsigned long saga::get_sd_package_api_version ()
References SAGA_VERSION_PACKAGE_SD_API.
template SAGA_STREAM_PACKAGE_EXPORT saga::stream::stream& saga::task::get_result< saga::stream::stream > ()
template SAGA_STREAM_PACKAGE_EXPORT saga::stream::server& saga::task::get_result< saga::stream::server > ()
template SAGA_STREAM_PACKAGE_EXPORT saga::stream::activity& saga::task::get_result< saga::stream::activity > ()
template SAGA_STREAM_PACKAGE_EXPORT std::vector<saga::stream::activity>& saga::task::get_result< std::vector< saga::stream::activity > > ()
SAGA_STREAM_PACKAGE_EXPORT unsigned long saga::get_stream_package_version ()
References SAGA_VERSION_PACKAGE_STREAM_FULL.
SAGA_STREAM_PACKAGE_EXPORT unsigned long saga::get_stream_package_api_version ()
References SAGA_VERSION_PACKAGE_STREAM_API.
template SAGA_EXPORT std::string& saga::task::get_result< std::string > ()
template SAGA_EXPORT std::vector<std::string>& saga::task::get_result< std::vector< std::string > > ()
template SAGA_EXPORT saga::size_t& saga::task::get_result< saga::size_t > ()
template SAGA_EXPORT saga::ssize_t& saga::task::get_result< saga::ssize_t > ()
template SAGA_EXPORT saga::off_t& saga::task::get_result< saga::off_t > ()
template SAGA_EXPORT saga::context& saga::task::get_result< saga::context > ()
template SAGA_EXPORT saga::url& saga::task::get_result< saga::url > ()
template SAGA_EXPORT std::vector<saga::url>& saga::task::get_result< std::vector< saga::url > > ()
SAGA_EXPORT std::ostream & saga::operator<< (std::ostream & os, url const & u)
Brief description starts here.
References saga::url::get_string().
SAGA_EXPORT std::istream & saga::operator>> (std::istream & is, url & u)
Brief description starts here.
SAGA_EXPORT bool saga::operator== (saga::url const & lhs, saga::url const & rhs)
Brief description starts here.
References saga::url::get_string().
SAGA_EXPORT bool saga::operator< (saga::url const & lhs, saga::url const & rhs)
Brief description starts here.
References saga::url::get_string().
SAGA_EXPORT unsigned long saga::get_engine_version (void)
Brief description starts here.
SAGA_EXPORT unsigned long saga::get_saga_version (void)
Brief description starts here.
References SAGA_VERSION_API.
SAGA_EXPORT char const saga::BOOST_PP_CAT (saga_check_version_ , BOOST_PP_CAT(SAGA_VERSION_MAJOR, BOOST_PP_CAT(_, SAGA_VERSION_MINOR)))
Brief description starts here.
Variable Documentation
char const saga::SAGA_CHECK_VERSION[] = BOOST_PP_STRINGIZE(SAGA_CHECK_VERSION)
Referenced by check_saga_version().