SAGA C++ API: saga-context.cpp File Reference
saga-context.cpp File Reference
#include <saga/saga.hpp>
Defines
#define COUNT 100
Functions
void dump_context (saga::context c)
int main (int argc, char *argv[])
Define Documentation
#define COUNT 100
Function Documentation
void dump_context (saga::context c)
References saga::detail::attribute< Derived >::attribute_is_vector(), saga::detail::attribute< Derived >::get_attribute(), saga::detail::attribute< Derived >::get_vector_attribute(), and saga::detail::attribute< Derived >::list_attributes().
Referenced by main().
int main (int argc, char * argv[])
References saga::attributes::context_type, dump_context(), and saga::session::list_contexts().