SAGA C++ API: saga-file.hpp File Reference
saga-file.hpp File Reference
#include <iostream>
#include <saga/saga-defs.hpp>
Defines
#define SAGA_GUARDED_EXEC(BLOCK)
Functions
void run_test (std::string fileURL)
void run_benchmarks (std::string smallFile, std::string bigFile, std::string targetDir, int copyIterations)
void file_cat (std::string fileURL)
void file_remove (std::string fileURL)
void file_copy (std::string sourceURL, std::string targetURL)
void file_move (std::string sourceURL, std::string targetURL)
void list_dir (std::string directoryURL)
Define Documentation
#define SAGA_GUARDED_EXEC (BLOCK)
Function Documentation
void run_test (std::string fileURL)
void run_benchmarks (std::string smallFile, std::string bigFile, std::string targetDir, int copyIterations)
References saga::task_container::add_task(), saga::name_space::entry::copy(), ITERATIONS, saga::filesystem::Overwrite, SAGA_GUARDED_EXEC, and saga::task_container::wait().
Referenced by main().
void file_cat (std::string fileURL)
References saga::buffer(), saga::filesystem::Read, and SAGA_GUARDED_EXEC.
Referenced by main().
void file_remove (std::string fileURL)
References saga::filesystem::ReadWrite, and SAGA_GUARDED_EXEC.
Referenced by main().
void file_copy (std::string sourceURL, std::string targetURL)
References saga::filesystem::Read, and SAGA_GUARDED_EXEC.
Referenced by main().
void file_move (std::string sourceURL, std::string targetURL)
References saga::filesystem::ReadWrite, and SAGA_GUARDED_EXEC.
Referenced by main().
void list_dir (std::string directoryURL)
References SAGA_GUARDED_EXEC.
Referenced by main().