SAGA C++ API: saga-replica.hpp File Reference
saga-replica.hpp File Reference
#include <iostream>
#include <saga/saga-defs.hpp>
Defines
#define SAGA_GUARDED_EXEC(BLOCK)
Functions
void replica_add_lfn (std::string lfnURL)
void replica_remove_lfn (std::string lfnURL)
void replica_list_directory (std::string lfnURL)
void replica_list_pfns (std::string lfn)
void replica_list_attributes (std::string lfn)
void replica_set_attribute (std::string lfnURL, std::string key, std::string val)
void replica_remove_attribute (std::string lfnURL, std::string key)
void replica_add_pfn (std::string lfnURL, std::string pfnURL)
void replica_remove_pfn (std::string lfnURL, std::string pfnURL)
Define Documentation
#define SAGA_GUARDED_EXEC (BLOCK)
Function Documentation
void replica_add_lfn (std::string lfnURL)
References saga::replica::Create, and SAGA_GUARDED_EXEC.
Referenced by main().
void replica_remove_lfn (std::string lfnURL)
References saga::replica::ReadWrite, and SAGA_GUARDED_EXEC.
Referenced by main().
void replica_list_directory (std::string lfnURL)
References SAGA_GUARDED_EXEC.
Referenced by main().
void replica_list_pfns (std::string lfn)
References SAGA_GUARDED_EXEC.
Referenced by main().
void replica_list_attributes (std::string lfn)
References SAGA_GUARDED_EXEC.
Referenced by main().
void replica_set_attribute (std::string lfnURL, std::string key, std::string val)
References saga::replica::ReadWrite, and SAGA_GUARDED_EXEC.
Referenced by main().
void replica_remove_attribute (std::string lfnURL, std::string key)
References SAGA_GUARDED_EXEC.
Referenced by main().
void replica_add_pfn (std::string lfnURL, std::string pfnURL)
References SAGA_GUARDED_EXEC, and saga::replica::Write.
Referenced by main().
void replica_remove_pfn (std::string lfnURL, std::string pfnURL)
References SAGA_GUARDED_EXEC, and saga::replica::Write.
Referenced by main().