SAGA C++ API: saga-job.hpp File Reference
saga-job.hpp File Reference
#include <iostream>
#include <saga/saga-defs.hpp>
Defines
#define SAGA_GUARDED_EXEC(BLOCK)
Functions
void run_test (std::string fileURL)
void run_benchmarks (std::string rmURL)
void job_run (std::string rm_url, std::string exe, std::vector< std::string > args)
void job_submit (std::string rm_url, std::string exe, std::vector< std::string > args)
void job_state (std::string rm_url, std::string job_id)
void job_suspend (std::string rm_url, std::string job_id)
void job_resume (std::string rm_url, std::string job_id)
Define Documentation
#define SAGA_GUARDED_EXEC (BLOCK)
Function Documentation
void run_test (std::string fileURL)
References saga::job::service::create_job(), saga::job::job::run(), SAGA_GUARDED_EXEC, saga::detail::attribute< Derived >::set_attribute(), and saga::detail::attribute< Derived >::set_vector_attribute().
Referenced by main().
void run_benchmarks (std::string rmURL)
References saga::task_container::add_task(), saga::job::service::create_job(), ITERATIONS, saga::job::job::run(), SAGA_GUARDED_EXEC, saga::detail::attribute< Derived >::set_attribute(), and saga::task_container::wait().
void job_run (std::string rm_url, std::string exe, std::vector< std::string > args)
References saga::buffer(), saga::attributes::common_true, saga::job::service::create_job(), saga::job::attributes::description_arguments, saga::job::attributes::description_executable, saga::job::attributes::description_interactive, saga::job::Done, saga::job::job::get_state(), saga::job::job::get_stderr(), saga::job::job::get_stdin(), saga::job::job::get_stdout(), saga::job::job::run(), saga::job::Running, SAGA_GUARDED_EXEC, and saga::job::metrics::state.
Referenced by main().
void job_submit (std::string rm_url, std::string exe, std::vector< std::string > args)
References saga::attributes::common_false, saga::job::service::create_job(), saga::job::attributes::description_arguments, saga::job::attributes::description_executable, saga::job::attributes::description_interactive, saga::job::job::get_job_id(), saga::job::job::run(), SAGA_GUARDED_EXEC, saga::detail::attribute< Derived >::set_attribute(), and saga::detail::attribute< Derived >::set_vector_attribute().
Referenced by main().
void job_state (std::string rm_url, std::string job_id)
References saga::job::job::get_state(), saga::job::detail::get_state_name(), and SAGA_GUARDED_EXEC.
Referenced by main().
void job_suspend (std::string rm_url, std::string job_id)
References SAGA_GUARDED_EXEC.
Referenced by main().
void job_resume (std::string rm_url, std::string job_id)
References SAGA_GUARDED_EXEC.
Referenced by main().