SAGA C++ API: saga-replica.cpp File Reference
saga-replica.cpp File Reference
#include <iostream>
#include <string>
#include "saga-replica.hpp"
#include <cstdlib>
#include <cstring>
Functions
void printUsage ()
void ExitIfArgcLessThan (int n)
int main (int argc, char *argv[])
Variables
static int argc_
Function Documentation
void printUsage ()
void ExitIfArgcLessThan (int n)
References argc_, and printUsage().
int main (int argc, char * argv[])
References argc_, ExitIfArgcLessThan(), printUsage(), replica_add_lfn(), replica_add_pfn(), replica_list_attributes(), replica_list_directory(), replica_list_pfns(), replica_remove_attribute(), replica_remove_lfn(), replica_remove_pfn(), and replica_set_attribute().
Variable Documentation
int argc_ [static]