SAGA C++ API: saga::detail::attribute< Derived > Struct Template Reference
saga::detail::attribute< Derived > Struct Template Reference
#include <attribute.hpp>
Detailed Description
template<typename Derived>
struct saga::detail::attribute< Derived >
The SAGA attribute interface.
Classes implementing this interface maintain a set of attributes. These attributes can be considered as a pair of string-based key-value pairs attached to the object. This interface provies methods for querying, adding, and removing attributes.
Usage example:
saga::url lfn("rls://localhost//lfn.dat");
//logical_file implements the attribute interface
logical_file::logical_file lf (lfn);
std::vector<std::string> keys(lf.list_attributes());
std::vector<std::string>::const_iterator end = keys.end();
std::vector<std::string>::const_iterator key_it = keys.begin();
for(; key_it != end; ++key_it) { std::cout << lf.get_attribute(*key_it) << std::endl };
Public Types
typedef std::vector< std::string > strvec_type
Attribute string vector type.
typedef std::map< std::string,
std::string > strmap_type
Attribute string map type.
Public Member Functions
SAGA_SYMBOL_INTERNAL std::string get_attribute (std::string key) const
Gets an attribute value.
SAGA_SYMBOL_INTERNAL void set_attribute (std::string key, std::string value)
Sets an attribute to a value.
SAGA_SYMBOL_INTERNAL strvec_type get_vector_attribute (std::string key) const
Gets the array of values associated with an attribute.
SAGA_SYMBOL_INTERNAL void set_vector_attribute (std::string key, strvec_type value)
Sets an attribute to an array of values.
SAGA_SYMBOL_INTERNAL void remove_attribute (std::string key)
Removes an attribute.
SAGA_SYMBOL_INTERNAL strvec_type list_attributes () const
Gets the list of attribute keys.
SAGA_SYMBOL_INTERNAL strvec_type find_attributes (std::string pattern) const
Finds matching attributes.
SAGA_SYMBOL_INTERNAL bool attribute_exists (std::string key) const
Checks if the attribute exists.
SAGA_SYMBOL_INTERNAL bool attribute_is_readonly (std::string key) const
Checks the attribute mode.
SAGA_SYMBOL_INTERNAL bool attribute_is_writable (std::string key) const
Checks the attribute mode.
SAGA_SYMBOL_INTERNAL bool attribute_is_vector (std::string key) const
Checks if it is vector.
SAGA_SYMBOL_INTERNAL bool attribute_is_removable (std::string key) const
Checks the attribute mode.
Member Typedef Documentation
template<typename Derived> typedef std::vector<std::string> saga::detail::attribute< Derived >::strvec_type
Attribute string vector type.
template<typename Derived> typedef std::map<std::string, std::string> saga::detail::attribute< Derived >::strmap_type
Attribute string map type.
Member Function Documentation
template<typename Derived> SAGA_SYMBOL_INTERNAL std::string saga::detail::attribute< Derived >::get_attribute (std::string key) const [inline]
Gets an attribute value.
Parameters:
key Attribute key name
Returns:
String value of the attribute.
Referenced by dump_context(), and saga::metric::fire().
template<typename Derived> SAGA_SYMBOL_INTERNAL void saga::detail::attribute< Derived >::set_attribute (std::string key, std::string value) [inline]
Sets an attribute to a value.
Parameters:
key Attribute key name
value String value to set the attribute to
Referenced by job_submit(), run_benchmarks(), and run_test().
template<typename Derived> SAGA_SYMBOL_INTERNAL strvec_type saga::detail::attribute< Derived >::get_vector_attribute (std::string key) const [inline]
Gets the array of values associated with an attribute.
Parameters:
key Attribute key name
Returns:
String array of attribute values
Referenced by dump_context().
template<typename Derived> SAGA_SYMBOL_INTERNAL void saga::detail::attribute< Derived >::set_vector_attribute (std::string key, strvec_type value) [inline]
Sets an attribute to an array of values.
Parameters:
key Attribute key name
values String array of attribute values
Referenced by job_submit(), and run_test().
template<typename Derived> SAGA_SYMBOL_INTERNAL void saga::detail::attribute< Derived >::remove_attribute (std::string key) [inline]
Removes an attribute.
Parameters:
key Attribute key to be removed
template<typename Derived> SAGA_SYMBOL_INTERNAL strvec_type saga::detail::attribute< Derived >::list_attributes () const [inline]
Gets the list of attribute keys.
Returns:
Existing attribute keys
Referenced by dump_context().
template<typename Derived> SAGA_SYMBOL_INTERNAL strvec_type saga::detail::attribute< Derived >::find_attributes (std::string pattern) const [inline]
Finds matching attributes.
Parameters:
pattern Key name search pattern
Returns:
Matching attribute keys
template<typename Derived> SAGA_SYMBOL_INTERNAL bool saga::detail::attribute< Derived >::attribute_exists (std::string key) const [inline]
Checks if the attribute exists.
Parameters:
key Attribute key name
Returns:
true if the attribute exists, false otherwise
template<typename Derived> SAGA_SYMBOL_INTERNAL bool saga::detail::attribute< Derived >::attribute_is_readonly (std::string key) const [inline]
Checks the attribute mode.
Parameters:
key Attribute key name.
Returns:
true if the attribute is read-only, false otherwise
template<typename Derived> SAGA_SYMBOL_INTERNAL bool saga::detail::attribute< Derived >::attribute_is_writable (std::string key) const [inline]
Checks the attribute mode.
Parameters:
key Attribute key name.
Returns:
true if the attribute is writeable, false otherwise
template<typename Derived> SAGA_SYMBOL_INTERNAL bool saga::detail::attribute< Derived >::attribute_is_vector (std::string key) const [inline]
Checks if it is vector.
Parameters:
key Attribute key name.
Returns:
true if the attribute is a vector, false otherwise
Referenced by dump_context().
template<typename Derived> SAGA_SYMBOL_INTERNAL bool saga::detail::attribute< Derived >::attribute_is_removable (std::string key) const [inline]
Checks the attribute mode.
Parameters:
key Attribute key.
Returns:
true if the attribute is removable, false otherwise